import os
import json
import logging
import google.generativeai as genai

from github import Github, GithubException
from unidiff import PatchSet

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def get_diff(repo, pr_number):
    pull = repo.get_pull(pr_number)
    return pull.get_files(), pull.head.sha

def parse_and_filter_diff(file_list):
    prompt_context = ""
    valid_files = []
    
    for file in file_list:
        if file.status == "removed" or file.filename.endswith(('.md', '.lock')):
            continue
            
        patch = PatchSet(file.patch)
        file_context = f"File: {file.filename}\n"
        
        for hunk in patch:
            file_context += f"Hunk at line {hunk.source_start}:\n"
            for line in hunk:
                # Only send added lines to AI for focused review, while preserving context lines
                prefix = "+" if line.is_added else ("-" if line.is_removed else " ")
                # Explicitly mark target line numbers in the prompt to prevent hallucinations
                line_marker = f"[Line {line.target_line_no}]" if not line.is_removed else ""
                file_context += f"{prefix} {line_marker} {line.value}"
        
        prompt_context += file_context + "\n---\n"
        valid_files.append(file.filename)
        
    return prompt_context

def analyze_with_gemini(diff_context):
    """Call Gemini 2.5 Flash to generate JSON comments"""
    api_key = os.environ
    genai.configure(api_key=api_key)
    
    model = genai.GenerativeModel(
        "gemini-2.5-flash",
        system_instruction=SYSTEM_INSTRUCTION # See definition above
    )
    
    prompt = f"""
    Analyze the following code changes. 
    Remember strictly to output English comments only.
    
    CODE CHANGES:
    {diff_context}
    """
    
    try:
        response = model.generate_content(
            prompt,
            generation_config=genai.GenerationConfig(
                response_mime_type="application/json",
                response_schema=CodeReviewResponse # See Pydantic definition above
            )
        )
        return json.loads(response.text)
    except Exception as e:
        logger.error(f"Gemini inference failed: {e}")
        return {"comments": [], "summary": "AI Review failed."}

def post_github_review(repo, pr_number, commit_sha, review_data):
    """Convert AI results into a GitHub Review request"""
    pull = repo.get_pull(pr_number)
    comments_payload = []
    
    for item in review_data.get("comments", []):
        # Verify if the line number is within the change range (GitHub API limitation: can only comment on lines in the diff)
        # Complex line number validation logic is omitted here; strict matching is required in production
        comments_payload.append({
            "path": item["file_path"],
            "line": item["line_number"],
            "side": "RIGHT", # Usually comment on the added code side
            "body": f"**** {item['content']}"
        })
        
    if not comments_payload:
        logger.info("No issues found.")
        return

    try:
        pull.create_review(
            commit=repo.get_commit(commit_sha),
            body=f"{review_data['summary']}\n\n*Generated by Google Gemini 2.5 Flash*",
            event="COMMENT", # Or "REQUEST_CHANGES" if serious issues are found
            comments=comments_payload
        )
        logger.info("Review posted successfully.")
    except GithubException as e:
        logger.error(f"Failed to post review: {e}")

if __name__ == "__main__":
    g = Github(os.environ)
    repo = g.get_repo(os.environ)
    pr_num = int(os.environ)
    
    files, sha = get_diff(repo, pr_num)
    context = parse_and_filter_diff(files)
    
    # Simple token count protection to prevent overly long requests
    if len(context) > 3000000: # Estimated character limit
        logger.warning("Diff too large for processing.")
    else:
        ai_response = analyze_with_gemini(context)
        post_github_review(repo, pr_num, sha, ai_response)
